# Generated by Django 5.2.6 on 2025-09-17 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.department')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Pivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_date', models.DateField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.employee')),
            ],
            options={
                'db_table': 'Pivot',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='employees', through='company.Pivot', to='achievements.achievement'),
        ),
        migrations.AddConstraint(
            model_name='pivot',
            constraint=models.UniqueConstraint(fields=('achievement', 'employee', 'achievement_date'), name='unique_achievement_employee_date'),
        ),
    ]
